import {db,staffSession,text,safeUrl} from './client.js';
const $=id=>document.getElementById(id);let staff=null,people=[],canManage=false,loading=false;const name=id=>people.find(p=>p.user_id===id)?.display_name||'HLR staff';const fmt=v=>v?new Date(v).toLocaleString():'No date';const iso=v=>v?new Date(v).toISOString():null;const status=t=>$('team-status').textContent=t;const check=r=>{if(r.error)throw r.error;return r.data||[]};const card=(box,title,meta,body)=>{const c=text('article','',box);c.className='work-card';text('h3',title,c);text('p',meta,c).className='meta';if(body)text('p',body,c);return c};
async function load(){if(loading)return;loading=true;try{staff=await staffSession();$('logged-out').hidden=!!staff;$('workspace').hidden=!staff;if(!staff){status('Sign in to an approved active HLR HQ account.');return}people=check(await db.from('staff_profiles').select('user_id,display_name,role').eq('active',true));const options=(id,blank)=>{const select=$(id),old=select.value;select.replaceChildren();if(blank){const o=text('option',blank,select);o.value=''}people.forEach(p=>{const o=text('option',p.display_name,select);o.value=p.user_id});select.value=old};options('task-assignee','Unassigned');options('channel-owner','Not delegated yet');
const results=await Promise.all([db.from('hq_tasks').select('*').order('created_at',{ascending:false}).limit(100),db.from('hq_meetings').select('*').neq('status','cancelled').order('starts_at',{ascending:true}).limit(100),db.from('hlr_availability').select('*').gte('ends_at',new Date().toISOString()).order('starts_at'),db.from('hlr_team_posts').select('*').order('created_at',{ascending:false}).limit(50),db.from('hlr_channel_decisions').select('*').eq('channel_slug','podcast').order('created_at',{ascending:false}).limit(50),db.from('hlr_channels').select('slug,owner_user_id').eq('slug','podcast').maybeSingle(),db.from('hlr_channel_audit').select('*').order('occurred_at',{ascending:false}).limit(20)]);
const [tasks,meetings,available,posts,decisions]=results.slice(0,5).map(check);if(results[5].error)throw results[5].error;const channel=results[5].data;canManage=!!channel;$('owner-tools').hidden=staff.role!=='owner';$('channel-owner').value=channel?.owner_user_id||'';$('owner-status').textContent=channel?channel.owner_user_id?'Delegated channel owner: '+name(channel.owner_user_id):'Podcast owner not delegated yet. Mark can choose an approved staff account.':'Channel owner details are restricted. Ask Mark to delegate your station access.';
const active=tasks.filter(t=>!['completed','cancelled'].includes(t.status)),late=active.filter(t=>t.due_at&&new Date(t.due_at)<new Date());$('team-stats').replaceChildren();[active.length+' open tasks',late.length+' overdue',meetings.filter(m=>new Date(m.starts_at)>new Date()).length+' upcoming sessions'].forEach(t=>text('span',t,$('team-stats')));
$('task-list').replaceChildren();tasks.forEach(t=>{const c=card($('task-list'),t.title,(t.assignee_name||name(t.assignee_user_id))+' · '+(t.department||'Team')+' · '+t.priority+' · Due '+fmt(t.due_at),t.description);if(late.some(x=>x.id===t.id))c.classList.add('overdue');const select=text('select','',c);select.setAttribute('aria-label','Status for '+t.title);['todo','in_progress','waiting','needs_review','completed','cancelled'].forEach(s=>{const o=text('option',s.replaceAll('_',' '),select);o.value=s});select.value=t.status;select.addEventListener('change',()=>mutate(()=>db.from('hq_tasks').update({status:select.value}).eq('id',t.id),'Task status saved.'))});
$('schedule-list').replaceChildren();meetings.filter(m=>!m.ends_at||new Date(m.ends_at)>new Date()).forEach(m=>{const c=card($('schedule-list'),m.title,fmt(m.starts_at)+' → '+fmt(m.ends_at),m.agenda);const url=safeUrl(m.join_url);if(url){const a=text('a','Open session link',c);a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.className='btn'}const b=text('button','Download calendar event',c);b.className='btn';b.addEventListener('click',()=>calendar(m));const s=text('select','',c);s.setAttribute('aria-label','Session status for '+m.title);['proposed','scheduled','in_progress','completed','cancelled'].forEach(v=>{const o=text('option',v,s);o.value=v});s.value=m.status;s.addEventListener('change',()=>mutate(()=>db.from('hq_meetings').update({status:s.value}).eq('id',m.id),'Session updated.'))});
$('availability-list').replaceChildren();available.forEach(a=>card($('availability-list'),name(a.user_id)+' · '+a.availability,fmt(a.starts_at)+' → '+fmt(a.ends_at),a.note));$('post-list').replaceChildren();posts.forEach(p=>card($('post-list'),name(p.author_id)+' · '+p.channel,fmt(p.created_at),p.body));$('decision-list').replaceChildren();decisions.forEach(d=>{const c=card($('decision-list'),d.title,d.status+' · '+name(d.author_id)+' · '+fmt(d.created_at),d.rationale);if(canManage){const select=text('select','',c);select.setAttribute('aria-label','Decision status for '+d.title);['proposed','approved','declined','needs_changes'].forEach(v=>{const o=text('option',v.replaceAll('_',' '),select);o.value=v});select.value=d.status;select.addEventListener('change',()=>mutate(()=>db.from('hlr_channel_decisions').update({status:select.value}).eq('id',d.id),'Decision recorded.'))}});$('audit-list').replaceChildren();check(results[6]).forEach(a=>text('p',name(a.actor_id)+' · '+a.action.replaceAll('_',' ')+' · '+fmt(a.occurred_at),$('audit-list')));status('Connected as '+staff.display_name+' · Shared with approved HLR staff.');}catch(e){status('Workspace error: '+e.message)}finally{loading=false}}
async function mutate(fn,message,form){try{const r=await fn();if(r.error)throw r.error;if(form)form.reset();await load();status(message)}catch(e){status(e.message)}}
$('task-form').addEventListener('submit',e=>{e.preventDefault();const assignee=$('task-assignee').value;mutate(()=>db.from('hq_tasks').insert({title:$('task-title').value.trim(),description:$('task-description').value,assignee_user_id:assignee||null,assignee_name:assignee?name(assignee):'Unassigned',department:$('task-department').value,priority:$('task-priority').value,due_at:iso($('task-due').value),status:'todo',created_by:staff.user_id}),'Shared task created.',e.target)});
$('meeting-form').addEventListener('submit',e=>{e.preventDefault();const start=iso($('meeting-start').value),end=iso($('meeting-end').value);if(end<=start){status('Session end must be after its start.');return}const url=$('meeting-link').value;if(url&&!safeUrl(url)){status('Use an HTTPS session link.');return}mutate(()=>db.from('hq_meetings').insert({title:$('meeting-title').value.trim(),meeting_type:'team_session',organizer_user_id:staff.user_id,starts_at:start,ends_at:end,join_url:url||null,location_type:'video',agenda:$('meeting-agenda').value,status:'scheduled'}),'Session scheduled in HQ.',e.target)});
$('availability-form').addEventListener('submit',e=>{e.preventDefault();const start=iso($('available-start').value),end=iso($('available-end').value);if(end<=start){status('Availability end must be after its start.');return}mutate(()=>db.from('hlr_availability').insert({user_id:staff.user_id,starts_at:start,ends_at:end,availability:$('available-state').value,note:$('available-note').value}),'Availability posted.',e.target)});
$('post-form').addEventListener('submit',e=>{e.preventDefault();mutate(()=>db.from('hlr_team_posts').insert({author_id:staff.user_id,channel:$('post-channel').value,body:$('post-body').value.trim()}),'Posted to HLR team.',e.target)});
$('decision-form').addEventListener('submit',e=>{e.preventDefault();mutate(()=>db.from('hlr_channel_decisions').insert({channel_slug:'podcast',author_id:staff.user_id,title:$('decision-title').value.trim(),rationale:$('decision-body').value.trim(),status:'proposed'}),'Decision proposed.',e.target)});
$('assign-owner').addEventListener('click',()=>mutate(()=>db.from('hlr_channels').update({owner_user_id:$('channel-owner').value||null}).eq('slug','podcast'),'Podcast authority updated.'));
function calendar(m){const esc=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/[,;]/g,'\\$&');const dt=s=>new Date(s).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//HLR//Team Workspace//EN','BEGIN:VEVENT','UID:'+m.id+'@hustlelegendrecords.com','DTSTAMP:'+dt(new Date()),'DTSTART:'+dt(m.starts_at),'DTEND:'+dt(m.ends_at||m.starts_at),'SUMMARY:'+esc(m.title),'DESCRIPTION:'+esc(m.agenda),'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'})),a=document.createElement('a');a.href=url;a.download='hlr-session.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('refresh').addEventListener('click',load);load();const timer=setInterval(()=>{if(!document.hidden)load()},30000);window.addEventListener('pagehide',()=>clearInterval(timer));
