(() => {
'use strict';
const sb=window.supabase.createClient('https://frkzkgmmcfexudikcdef.supabase.co','sb_publishable_UlEz_-eBThXUgesLl036RQ_J_-Edto9',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let user=null,staff=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function init(){const {data:{session}}=await sb.auth.getSession();user=session?.user||null;if(!user)return $('status').textContent='Not signed in. Use the HLR Radio Control Room first.';const {data,error}=await sb.from('staff_profiles').select('*').eq('user_id',user.id).maybeSingle();if(error||!data?.active){$('status').textContent='Active HLR staff access is required.';return;}staff=data;$('authGate').classList.add('hidden');$('queue').classList.remove('hidden');load();}
async function load(){const {data,error}=await sb.from('artist_submissions').select('*').order('created_at',{ascending:true});const el=$('cards');if(error){el.innerHTML=`<div class="card">${esc(error.message)}</div>`;return;}el.innerHTML=data.length?'':'<div class="card">No artist submissions yet.</div>';data.forEach(s=>{const c=document.createElement('div');c.className='card';const routes=[s.wants_radio&&'Radio',s.wants_editorial&&'Editorial',s.wants_interview&&'Interview',s.wants_licensing&&'Licensing'].filter(Boolean).join(' · ');c.innerHTML=`<strong>${esc(s.artist_name)} — ${esc(s.track_title)}</strong> <span class="badge">${esc(String(s.status).replaceAll('_',' ').toUpperCase())}</span><div class="meta">${esc(routes||'General review')} · ${new Date(s.created_at).toLocaleString()}</div>${s.track_url?`<p><a class="btn" href="${esc(s.track_url)}" target="_blank" rel="noopener">OPEN REVIEW LINK</a></p>`:''}${s.storage_path?'<p><button class="btn" data-preview>PREVIEW PRIVATE AUDIO</button></p>':''}<p class="small">Rights: master ${s.master_controlled?'YES':'NO'} · publishing ${s.publishing_controlled?'YES':'NO'} · samples ${s.samples_cleared?'CLEARED/NO SAMPLES':'NOT CONFIRMED'} · clean ${s.clean_available?'YES':'NO'} · instrumental ${s.instrumental_available?'YES':'NO'}</p>${s.notes?`<p class="small">Pitch: ${esc(s.notes)}</p>`:''}<div class="field"><label>Decision / status</label><select data-status><option value="reviewing">Reviewing</option><option value="approved_radio">Approved — Radio</option><option value="approved_editorial">Approved — Editorial</option><option value="approved_interview">Approved — Interview</option><option value="licensing_ready">Licensing Ready</option><option value="scheduled">Scheduled</option><option value="declined">Declined</option><option value="archived">Archived</option></select></div><div class="field"><label>Artist-facing note</label><textarea data-note>${esc(s.decision_note||'')}</textarea></div><div class="toolbar"><button class="btn primary" data-save>SAVE DECISION</button></div>`;
c.querySelector('[data-status]').value=s.status==='submitted'?'reviewing':s.status;
if(s.storage_path)c.querySelector('[data-preview]').onclick=async()=>{const {data,error}=await sb.storage.from('hlr-artist-submissions').createSignedUrl(s.storage_path,300);if(error)return alert(error.message);window.open(data.signedUrl,'_blank','noopener');};
c.querySelector('[data-save]').onclick=async()=>{const status=c.querySelector('[data-status]').value,note=c.querySelector('[data-note]').value.trim()||null;const {error:updateError}=await sb.from('artist_submissions').update({status,decision_note:note,updated_at:new Date().toISOString()}).eq('id',s.id);if(updateError)return alert(updateError.message);await sb.from('artist_submission_reviews').insert({submission_id:s.id,reviewer_id:user.id,outcome:status,public_note:note});load();};
el.appendChild(c);});}
init();
})();
