(()=>{'use strict';
const $=id=>document.getElementById(id),status=text=>{$('status').textContent=text};
let stream=null,recorder=null,chunks=[],takeUrl=null,mediaUrl=null,timer=null,start=0,pending=false;
const setControls=()=>{const recording=recorder&&recorder.state!=='inactive';$('connect').disabled=!!stream||pending;$('mode').disabled=!!stream||pending;$('record').disabled=!stream||recording||pending;$('stop').disabled=!recording;$('disconnect').disabled=!stream||recording;};
const stopTracks=()=>{if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('preview').srcObject=null;$('preview').hidden=true;$('preview-empty').hidden=false;setControls();};
$('connect').addEventListener('click',async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status('Recording is unavailable in this browser. Try a current Chrome, Edge, Firefox or Safari browser.');return;}pending=true;setControls();status('Waiting for device permission…');try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:$('mode').value==='video'?{width:{ideal:1280},height:{ideal:720}}:false});if(stream.getVideoTracks().length){$('preview').srcObject=stream;$('preview').hidden=false;$('preview-empty').hidden=true;}else{$('preview-empty').textContent='Microphone connected. Audio mode is ready.';}stream.getTracks().forEach(track=>track.addEventListener('ended',()=>{if(recorder?.state==='recording')recorder.stop();stopTracks();status('Device disconnected. Review and download any completed take.');}));status('Devices connected. Press Record when ready.');}catch(e){stopTracks();status(e.name==='NotAllowedError'?'Device access was declined. Allow your microphone / camera in browser settings to record.':e.name==='NotFoundError'?'No matching microphone or camera was found. Check your device and recording mode.':'Could not connect devices. Close other apps using the device and try again.');}finally{pending=false;setControls();}});
$('record').addEventListener('click',()=>{if(!stream||recorder?.state==='recording')return;const video=stream.getVideoTracks().length>0;const types=video?['video/webm;codecs=vp8,opus','video/webm','video/mp4']:['audio/webm;codecs=opus','audio/webm','audio/mp4'];const mime=types.find(t=>MediaRecorder.isTypeSupported(t));try{recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=()=>{status('Recording failed. Stop and review any recovered take.');};recorder.onstop=()=>{clearInterval(timer);timer=null;const blob=new Blob(chunks,{type:recorder.mimeType|| (video?'video/webm':'audio/webm')});if(!blob.size){status('No recording data was captured. Check the device and try again.');setControls();return;}if(takeUrl)URL.revokeObjectURL(takeUrl);takeUrl=URL.createObjectURL(blob);const player=$(video?'video-review':'audio-review');$('audio-review').hidden=!!video;$('video-review').hidden=!video;player.src=takeUrl;$('review').hidden=false;$('download').href=takeUrl;const ext=blob.type.includes('mp4')?'mp4':'webm';$('download').download=`HLR-Podcast-${new Date().toISOString().replace(/[:.]/g,'-')}.${ext}`;status('Take ready. Play it back, then download before leaving this page.');setControls();};recorder.start(1000);$('review').hidden=true;start=Date.now();$('timer').textContent='00:00';timer=setInterval(()=>{const elapsed=Math.floor((Date.now()-start)/1000);$('timer').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;},250);status('Recording. Press Stop to finish this take.');setControls();}catch(e){status('This browser could not start recording. Try another recording mode or browser.');setControls();}});
$('stop').addEventListener('click',()=>{if(recorder?.state==='recording'){recorder.stop();pending=true;$('stop').disabled=true;status('Finishing recording…');recorder.addEventListener('stop',()=>{pending=false;setControls();},{once:true});}});
$('disconnect').addEventListener('click',()=>{stopTracks();$('preview-empty').textContent='Devices disconnected.';status('Devices disconnected. Existing downloads and review are still available.');});
$('media-file').addEventListener('change',()=>{const file=$('media-file').files[0];if(!file)return;const isVideo=file.type.startsWith('video/'),isAudio=file.type.startsWith('audio/');if(!isVideo&&!isAudio){status('Choose a supported audio or video file.');return;}for(const id of ['media-player','media-audio']){$(id).pause();$(id).removeAttribute('src');$(id).hidden=true;}if(mediaUrl)URL.revokeObjectURL(mediaUrl);mediaUrl=URL.createObjectURL(file);const player=$(isVideo?'media-player':'media-audio');player.src=mediaUrl;player.hidden=false;player.onerror=()=>status('This browser cannot play that file format. Try MP4 video or MP3 audio.');});
const guidance={'Starting Soon':'Confirm devices, headphones and your opening notes before the session.','Host Solo':'Introduce the topic, check your microphone level and record a short test take.','Host + Guest':'Connect your guest through your call / OBS setup and confirm both voices before recording there.','Four Person':'Use the four-person layout in OBS. Check every participant’s audio and camera separately.','Reaction / Media':'Open your reference file in the media desk. For a combined camera / media recording, use OBS.','End Screen':'Close with credits, the next episode and where listeners can find HLR.'};
const key='hlr-podcast-plan-v1';try{const saved=JSON.parse(localStorage.getItem(key)||'{}');$('session-title').value=saved.title||'';$('notes').value=saved.notes||'';if(guidance[saved.scene])$('scene').value=saved.scene;}catch(e){}
const save=()=>{try{localStorage.setItem(key,JSON.stringify({title:$('session-title').value,notes:$('notes').value,scene:$('scene').value}));}catch(e){$('notes-status').textContent='Browser storage is unavailable. Download your run sheet to keep it.';}};
const scene=()=>{$('scene-note').textContent=guidance[$('scene').value];save();};$('scene').addEventListener('change',scene);$('session-title').addEventListener('input',save);$('notes').addEventListener('input',save);scene();
$('download-notes').addEventListener('click',()=>{const text=`HLR PODCAST — SESSION RUN SHEET\n\nTitle: ${$('session-title').value||'Untitled session'}\nSegment: ${$('scene').value}\n\n${$('notes').value}\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='HLR-Podcast-Run-Sheet.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
addEventListener('beforeunload',e=>{if(stream||takeUrl){e.preventDefault();e.returnValue='';}});addEventListener('pagehide',()=>{clearInterval(timer);if(stream)stream.getTracks().forEach(t=>t.stop());if(takeUrl)URL.revokeObjectURL(takeUrl);if(mediaUrl)URL.revokeObjectURL(mediaUrl);});setControls();
})();
